import argparse
from nt_trader.runner import NewsTrader
from nt_trader.config import load_config, merge_config_into_args


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Trade on news sentiment using Finnhub + Alpaca (paper/live).")
    parser.add_argument("--config", type=str, default=None, help="Path to JSON config (defaults to ./config.json if present)")
    parser.add_argument("--tickers", type=str, default="AAPL,MSFT,TSLA", help="Comma-separated tickers to evaluate")
    parser.add_argument("--sp500", action="store_true", help="Use the S&P 500 constituents (overrides --tickers)")
    parser.add_argument("--limit-tickers", type=int, default=0, help="If >0, limit universe to this many tickers")
    parser.add_argument("--randomize", action="store_true", help="Shuffle the universe before limiting")

    parser.add_argument("--use-gpt", action="store_true", help="Use GPT to analyze news (requires OPENAI_API_KEY or openai.json)")
    parser.add_argument("--use-gpt-decision", action="store_true", help="Use GPT's suggested decision when available")
    parser.add_argument("--gpt-model", type=str, default="gpt-4o-mini", help="OpenAI model for news analysis")
    parser.add_argument("--gpt-weight", type=float, default=0.5, help="Weight for GPT vs VADER per item (0..1)")
    parser.add_argument("--macro-weight", type=float, default=0.3, help="Weight factor applied to macro (GDELT) items if they affect sentiment")
    parser.add_argument("--gpt-max-news", type=int, default=3, help="Max news items per ticker to send to GPT")
    parser.add_argument("--gpt-timeout", type=float, default=20.0, help="Timeout (seconds) for GPT API calls")
    parser.add_argument("--gpt-decision-min-confidence", type=float, default=0.0, help="Minimum avg GPT confidence to trust decision in hybrid mode")
    parser.add_argument("--strategy", type=str, default="rule", choices=["rule","gpt","hybrid"], help="Decision source: rule thresholds, GPT, or hybrid")
    parser.add_argument("--macro-affects-sentiment", action="store_true", default=False, help="If true, macro (GDELT) events contribute to per-stock sentiment")
    parser.add_argument("--gpt-min-abs-vader", type=float, default=0.1, help="Only call GPT if |VADER| exceeds this")
    parser.add_argument("--gpt-min-window-move-pct", type=float, default=0.5, help="Only call GPT if price window change exceeds this percent")

    parser.add_argument("--from-date", type=str, default=None, help="Start date YYYY-MM-DD (defaults to 3 days ago)")
    parser.add_argument("--to-date", type=str, default=None, help="End date YYYY-MM-DD (defaults to today)")
    parser.add_argument("--trade", action="store_true", help="Place orders on Alpaca (paper by default). Otherwise dry-run.")
    parser.add_argument("--alpaca-env", type=str, choices=["paper","live"], default="paper", help="Alpaca trading environment (paper|live)")
    parser.add_argument("--confirm-live-trade", action="store_true", help="Required to enable live trading when --alpaca-env live")
    parser.add_argument("--dollars-per-trade", type=float, default=1000.0, help="USD per position when entering")
    parser.add_argument("--pos-threshold", type=float, default=0.2, help="Sentiment threshold to open/flip a position")
    parser.add_argument("--close-threshold", type=float, default=0.05, help="If |sentiment| falls below this, close position")
    parser.add_argument("--max-news", type=int, default=20, help="Max recent news items to score per ticker")
    parser.add_argument("--sleep", type=float, default=0.7, help="Seconds to sleep between API calls")
    # Factor model (price-based context) blended into sentiment
    parser.add_argument("--factor-weight", type=float, default=0.2, help="Weight of price factors in final sentiment (0..1)")
    parser.add_argument("--factor-window-chg-scale", type=float, default=2.0, help="% change that maps to +/-1 factor score")
    parser.add_argument("--factor-vol-penalty-scale", type=float, default=10.0, help="% vol that maps to max penalty")
    parser.add_argument("--factor-trend-bonus", type=float, default=0.1, help="Bonus added for up trend (negative for down)")
    parser.add_argument("--factor-range-bias-weight", type=float, default=0.1, help="Weight for intrawindow range position bias")

    # Looping + cooldowns
    parser.add_argument("--loop", action="store_true", help="Continuously run and poll for news/decisions")
    parser.add_argument("--poll-seconds", type=float, default=60.0, help="Main loop sleep between cycles")
    parser.add_argument("--news-poll-seconds", type=float, default=0.0, help="Minimum seconds between news fetch per symbol")
    parser.add_argument("--price-poll-seconds", type=float, default=0.0, help="Minimum seconds between price updates per symbol")
    parser.add_argument("--trade-cooldown-minutes", type=float, default=0.0, help="Minimum minutes between trades for the same symbol (entries only)")
    parser.add_argument("--state-file", type=str, default="nt_state.json", help="Path to persistent state file (cooldowns)")
    parser.add_argument("--log-file", type=str, default="logs/trades.csv", help="CSV log file for trade events")
    parser.add_argument("--decisions-log-file", type=str, default="logs/decisions.csv", help="CSV file for per-decision snapshots")
    parser.add_argument("--clamp-news-rate", dest="clamp_news_rate", action="store_true", default=True, help="Clamp news poll rate to 1..5x/min in loop mode")
    parser.add_argument("--no-clamp-news-rate", dest="clamp_news_rate", action="store_false", help="Disable rate clamping")

    # Price history + cache
    parser.add_argument("--price-history-window-min", type=float, default=30.0, help="Minutes of price history to keep per symbol")
    parser.add_argument("--price-history-points", type=int, default=10, help="Max price points to include in GPT context")
    parser.add_argument("--max-seen-news-per-symbol", type=int, default=500, help="Max seen news IDs cached per symbol")

    # GDELT macro events
    parser.add_argument("--gdelt", action="store_true", help="Include GDELT macro political/economic events")
    parser.add_argument("--gdelt-themes", type=str, default="ECON_INFLATION,ECON_INTEREST_RATE,ECON_GDP,ECON_UNEMPLOYMENT,ELECTION_GENERAL", help="Comma-separated GDELT themes to include")
    parser.add_argument("--gdelt-max-records", type=int, default=30, help="Max GDELT records to fetch per refresh")
    parser.add_argument("--gdelt-timespan-min", type=int, default=180, help="Lookback window in minutes for GDELT fetch")
    parser.add_argument("--gdelt-poll-seconds", type=float, default=60.0, help="Cooldown between GDELT refreshes")

    # Market hours controls
    parser.add_argument("--market-only-trade", action="store_true", default=True, help="Only place trades during regular market hours")
    parser.add_argument("--no-market-only-trade", dest="market_only_trade", action="store_false")
    parser.add_argument("--market-only-price", action="store_true", default=True, help="Only refresh quotes during regular market hours (reuse cache otherwise)")
    parser.add_argument("--no-market-only-price", dest="market_only_price", action="store_false")
    parser.add_argument("--market-timezone", type=str, default="America/New_York", help="Timezone for market hours (default NYSE)")

    # Finnhub backoff controls
    parser.add_argument("--finnhub-backoff", dest="finnhub_backoff", action="store_true", default=True, help="Exponential backoff on Finnhub errors")
    parser.add_argument("--no-finnhub-backoff", dest="finnhub_backoff", action="store_false")
    parser.add_argument("--finnhub-backoff-start-seconds", type=float, default=2.0, help="Initial backoff after first error")
    parser.add_argument("--finnhub-backoff-max-seconds", type=float, default=120.0, help="Maximum backoff sleep between Finnhub calls")
    parser.add_argument("--finnhub-backoff-multiplier", type=float, default=2.0, help="Backoff growth factor on consecutive errors")
    parser.add_argument("--finnhub-backoff-decay", type=float, default=0.5, help="Decay factor after successful Finnhub call (0..1)")

    # Global Finnhub rate limiting and batching
    parser.add_argument("--finnhub-max-rpm", type=int, default=50, help="Global cap of Finnhub requests per minute (0=disabled)")
    parser.add_argument("--finnhub-min-interval-seconds", type=float, default=0.25, help="Minimum seconds between Finnhub requests")
    parser.add_argument("--symbols-per-batch", type=int, default=50, help="How many tickers to process before a batch sleep")
    parser.add_argument("--batch-sleep-seconds", type=float, default=5.0, help="Sleep between batches of symbols")

    # Local news cache
    parser.add_argument("--news-cache-file", type=str, default="logs/news_cache.json", help="Path to local news cache file")
    parser.add_argument("--news-cache-ttl-seconds", type=int, default=300, help="Use cached news if fresher than this many seconds")
    parser.add_argument("--news-cache-max-items", type=int, default=50, help="Max cached news items per symbol")

    # Alpaca Data (batch snapshots)
    parser.add_argument("--use-alpaca-data", action="store_true", help="Use Alpaca Data snapshots to batch-fetch prices")
    parser.add_argument("--alpaca-data-base-url", type=str, default="https://data.alpaca.markets/v2", help="Override Alpaca Data base URL for snapshots")
    parser.add_argument("--snapshot-offhours-prices", action="store_true", default=False, help="Allow Alpaca snapshots off-hours to seed prices (trading still market-only)")

    # Risk and order controls
    parser.add_argument("--max-open-positions", type=int, default=20, help="Max number of open positions allowed")
    parser.add_argument("--max-usd-per-symbol", type=float, default=2000.0, help="Max dollar exposure per single symbol")
    # Order sizing
    parser.add_argument("--order-size-mode", type=str, choices=["auto","shares","dollars"], default="auto", help="Size orders by shares, dollars (notional), or auto")
    parser.add_argument("--shares-per-trade", type=int, default=0, help="If >0 and mode=shares, buy this many shares per entry")
    parser.add_argument("--use-bracket", action="store_true", help="Use Alpaca bracket orders with TP/SL")
    parser.add_argument("--tp-pct", type=float, default=0.02, help="Take profit percent for bracket (e.g., 0.02 = 2%)")
    parser.add_argument("--sl-pct", type=float, default=0.01, help="Stop loss percent for bracket (e.g., 0.01 = 1%)")
    # Dynamic bracket (per-stock TP/SL from news)
    parser.add_argument("--dynamic-bracket", action="store_true", help="Enable dynamic per-stock TP/SL from news analysis")
    parser.add_argument("--tp-pct-min", type=float, default=None, help="Min TP percent (decimal) when dynamic-bracket is on")
    parser.add_argument("--tp-pct-max", type=float, default=None, help="Max TP percent (decimal) when dynamic-bracket is on")
    parser.add_argument("--sl-pct-min", type=float, default=None, help="Min SL percent (decimal) when dynamic-bracket is on")
    parser.add_argument("--sl-pct-max", type=float, default=None, help="Max SL percent (decimal) when dynamic-bracket is on")
    parser.add_argument("--rr-multiple", type=float, default=2.0, help="Target reward:risk multiple when deriving SL from TP")
    parser.add_argument("--scale-by-gpt-conf", action="store_true", default=True, help="Scale TP by GPT confidence if available")
    parser.add_argument("--long-only", action="store_true", default=True, help="Disable shorts; only buy to open and sell to close")
    parser.add_argument("--allocation-pct", type=float, default=0.2, help="Fraction of buying power allocated across positions (0..1)")
    parser.add_argument("--dual-horizon", action="store_true", help="Split positions into core (long-term) and tactical (short-term)")
    parser.add_argument("--core-allocation-pct", type=float, default=0.6, help="Fraction of each new position assigned to core holdings when dual-horizon is enabled")
    parser.add_argument("--core-use-bracket", action="store_true", help="Use bracket for core leg (long-term)")
    parser.add_argument("--core-tp-pct", type=float, default=0.06, help="Core leg take-profit percent (e.g., 0.06 = 6%)")
    parser.add_argument("--core-sl-pct", type=float, default=0.03, help="Core leg stop-loss percent (e.g., 0.03 = 3%)")
    parser.add_argument("--core-strong-exit-sentiment", type=float, default=-0.2, help="Close core if sentiment <= this (strong negative)")
    parser.add_argument("--in-pos-exit-sentiment", type=float, default=-0.05, help="When already holding a long, only close if sentiment <= this")
    # Drawdown/price-fall stops for holdings
    parser.add_argument("--enable-drawdown-stop", action="store_true", help="Enable forced close if price keeps dropping and exceeds drop threshold from entry")
    parser.add_argument("--dd-max-drop-pct", type=float, default=5.0, help="Max allowed drop (%) from entry before considering forced close")
    parser.add_argument("--dd-window-min", type=float, default=15.0, help="Minutes window to evaluate recent drop trend")
    parser.add_argument("--dd-window-drop-pct", type=float, default=1.0, help="Required drop (%) over the window to qualify as 'keep dropping'")
    parser.add_argument("--dd-min-consecutive-down", type=int, default=3, help="Require at least this many consecutive down ticks in the window")
    parser.add_argument("--dd-require-both", action="store_true", help="Require BOTH window drop and consecutive-down conditions (in addition to entry drop) for forced close")
    # Holdings watcher: dedicated thread for open positions
    parser.add_argument("--holdings-watcher", action="store_true", help="Track current holdings in a separate thread")
    parser.add_argument("--holdings-poll-seconds", type=float, default=20.0, help="Polling interval for holdings watcher thread")
    # PDT + Tax awareness
    parser.add_argument("--enforce-pdt", action="store_true", help="Respect PDT limits for < $25k equity accounts")
    parser.add_argument("--pdt-min-equity", type=float, default=25000.0, help="Equity threshold for PDT checks")
    parser.add_argument("--max-daytrades-5d", type=int, default=3, help="Max day trades over 5 trading days before blocking entries")
    parser.add_argument("--pdt-allow-risk-exit", action="store_true", default=True, help="Allow forced exits even if it creates a new day trade when PDT limit reached")
    parser.add_argument("--tax-aware", action="store_true", help="Adjust closing behavior to account for capital gains considerations")
    parser.add_argument("--ltcg-days", type=int, default=365, help=">= days held to be considered long-term for taxes")
    parser.add_argument("--tax-min-hold-days", type=int, default=0, help="Minimum days to hold before closing for small signals when tax-aware")
    parser.add_argument("--tax-min-profit-usd-to-close-short-term", type=float, default=0.0, help="If tax-aware and short-term, require at least this profit to close (unless strong negative)")
    # Per-symbol cap as percent of account equity
    parser.add_argument("--max-pct-per-symbol", type=float, default=0.0, help="Max fraction (0..1) of account equity allowed per symbol (0 disables)")
    return parser.parse_args()


def main() -> None:
    parser = argparse.ArgumentParser(add_help=False)
    # Build the same parser to compute defaults and support merging
    args = parse_args()
    # Merge config values (CLI flags win over config)
    cfg = load_config(getattr(args, "config", None))
    # Reconstruct a real parser to pass to the merger
    real_parser = argparse.ArgumentParser(description="Trade on news sentiment using Finnhub + Alpaca (paper/live).")
    # Repeat definitions to capture defaults
    real_parser.add_argument("--config", type=str, default=None)
    real_parser.add_argument("--tickers", type=str, default="AAPL,MSFT,TSLA")
    real_parser.add_argument("--sp500", action="store_true")
    real_parser.add_argument("--limit-tickers", type=int, default=0)
    real_parser.add_argument("--randomize", action="store_true")
    real_parser.add_argument("--use-gpt", action="store_true")
    real_parser.add_argument("--use-gpt-decision", action="store_true")
    real_parser.add_argument("--gpt-model", type=str, default="gpt-4o-mini")
    real_parser.add_argument("--gpt-weight", type=float, default=0.5)
    real_parser.add_argument("--macro-weight", type=float, default=0.3)
    real_parser.add_argument("--gpt-max-news", type=int, default=3)
    real_parser.add_argument("--gpt-timeout", type=float, default=20.0)
    real_parser.add_argument("--gpt-decision-min-confidence", type=float, default=0.0)
    real_parser.add_argument("--strategy", type=str, default="rule")
    real_parser.add_argument("--macro-affects-sentiment", action="store_true", default=False)
    real_parser.add_argument("--gpt-min-abs-vader", type=float, default=0.1)
    real_parser.add_argument("--gpt-min-window-move-pct", type=float, default=0.5)
    real_parser.add_argument("--from-date", type=str, default=None)
    real_parser.add_argument("--to-date", type=str, default=None)
    real_parser.add_argument("--trade", action="store_true")
    real_parser.add_argument("--alpaca-env", type=str, choices=["paper","live"], default="paper")
    real_parser.add_argument("--confirm-live-trade", action="store_true")
    real_parser.add_argument("--dollars-per-trade", type=float, default=1000.0)
    real_parser.add_argument("--pos-threshold", type=float, default=0.2)
    real_parser.add_argument("--close-threshold", type=float, default=0.05)
    real_parser.add_argument("--max-news", type=int, default=20)
    real_parser.add_argument("--sleep", type=float, default=0.7)
    real_parser.add_argument("--factor-weight", type=float, default=0.2)
    real_parser.add_argument("--factor-window-chg-scale", type=float, default=2.0)
    real_parser.add_argument("--factor-vol-penalty-scale", type=float, default=10.0)
    real_parser.add_argument("--factor-trend-bonus", type=float, default=0.1)
    real_parser.add_argument("--factor-range-bias-weight", type=float, default=0.1)
    real_parser.add_argument("--loop", action="store_true")
    real_parser.add_argument("--poll-seconds", type=float, default=60.0)
    real_parser.add_argument("--news-poll-seconds", type=float, default=0.0)
    real_parser.add_argument("--price-poll-seconds", type=float, default=0.0)
    real_parser.add_argument("--trade-cooldown-minutes", type=float, default=0.0)
    real_parser.add_argument("--state-file", type=str, default="nt_state.json")
    real_parser.add_argument("--log-file", type=str, default="logs/trades.csv")
    real_parser.add_argument("--decisions-log-file", type=str, default="logs/decisions.csv")
    real_parser.add_argument("--clamp-news-rate", dest="clamp_news_rate", action="store_true", default=True)
    real_parser.add_argument("--no-clamp-news-rate", dest="clamp_news_rate", action="store_false")
    real_parser.add_argument("--price-history-window-min", type=float, default=30.0)
    real_parser.add_argument("--price-history-points", type=int, default=10)
    real_parser.add_argument("--max-seen-news-per-symbol", type=int, default=500)
    real_parser.add_argument("--gdelt", action="store_true")
    real_parser.add_argument("--gdelt-themes", type=str, default="ECON_INFLATION,ECON_INTEREST_RATE,ECON_GDP,ECON_UNEMPLOYMENT,ELECTION_GENERAL")
    real_parser.add_argument("--gdelt-max-records", type=int, default=30)
    real_parser.add_argument("--gdelt-timespan-min", type=int, default=180)
    real_parser.add_argument("--gdelt-poll-seconds", type=float, default=60.0)
    real_parser.add_argument("--market-only-trade", action="store_true", default=True)
    real_parser.add_argument("--no-market-only-trade", dest="market_only_trade", action="store_false")
    real_parser.add_argument("--market-only-price", action="store_true", default=True)
    real_parser.add_argument("--no-market-only-price", dest="market_only_price", action="store_false")
    real_parser.add_argument("--market-timezone", type=str, default="America/New_York")
    real_parser.add_argument("--finnhub-backoff", dest="finnhub_backoff", action="store_true", default=True)
    real_parser.add_argument("--no-finnhub-backoff", dest="finnhub_backoff", action="store_false")
    real_parser.add_argument("--finnhub-backoff-start-seconds", type=float, default=2.0)
    real_parser.add_argument("--finnhub-backoff-max-seconds", type=float, default=120.0)
    real_parser.add_argument("--finnhub-backoff-multiplier", type=float, default=2.0)
    real_parser.add_argument("--finnhub-backoff-decay", type=float, default=0.5)
    real_parser.add_argument("--finnhub-max-rpm", type=int, default=50)
    real_parser.add_argument("--finnhub-min-interval-seconds", type=float, default=0.25)
    real_parser.add_argument("--symbols-per-batch", type=int, default=50)
    real_parser.add_argument("--batch-sleep-seconds", type=float, default=5.0)
    real_parser.add_argument("--use-alpaca-data", action="store_true")
    real_parser.add_argument("--alpaca-data-base-url", type=str, default="https://data.alpaca.markets/v2")
    real_parser.add_argument("--snapshot-offhours-prices", action="store_true", default=False)
    real_parser.add_argument("--news-cache-file", type=str, default="logs/news_cache.json")
    real_parser.add_argument("--news-cache-ttl-seconds", type=int, default=300)
    real_parser.add_argument("--news-cache-max-items", type=int, default=50)
    real_parser.add_argument("--max-open-positions", type=int, default=20)
    real_parser.add_argument("--max-usd-per-symbol", type=float, default=2000.0)
    real_parser.add_argument("--max-pct-per-symbol", type=float, default=0.0)
    real_parser.add_argument("--order-size-mode", type=str, choices=["auto","shares","dollars"], default="auto")
    real_parser.add_argument("--shares-per-trade", type=int, default=0)
    real_parser.add_argument("--enforce-pdt", action="store_true")
    real_parser.add_argument("--pdt-min-equity", type=float, default=25000.0)
    real_parser.add_argument("--max-daytrades-5d", type=int, default=3)
    real_parser.add_argument("--pdt-allow-risk-exit", action="store_true", default=True)
    real_parser.add_argument("--tax-aware", action="store_true")
    real_parser.add_argument("--ltcg-days", type=int, default=365)
    real_parser.add_argument("--tax-min-hold-days", type=int, default=0)
    real_parser.add_argument("--tax-min-profit-usd-to-close-short-term", type=float, default=0.0)
    real_parser.add_argument("--use-bracket", action="store_true")
    real_parser.add_argument("--tp-pct", type=float, default=0.02)
    real_parser.add_argument("--sl-pct", type=float, default=0.01)
    real_parser.add_argument("--dynamic-bracket", action="store_true")
    real_parser.add_argument("--tp-pct-min", type=float, default=None)
    real_parser.add_argument("--tp-pct-max", type=float, default=None)
    real_parser.add_argument("--sl-pct-min", type=float, default=None)
    real_parser.add_argument("--sl-pct-max", type=float, default=None)
    real_parser.add_argument("--rr-multiple", type=float, default=2.0)
    real_parser.add_argument("--scale-by-gpt-conf", action="store_true", default=True)
    real_parser.add_argument("--long-only", action="store_true", default=True)
    real_parser.add_argument("--allocation-pct", type=float, default=0.2)
    real_parser.add_argument("--dual-horizon", action="store_true")
    real_parser.add_argument("--core-allocation-pct", type=float, default=0.6)
    real_parser.add_argument("--core-use-bracket", action="store_true")
    real_parser.add_argument("--core-tp-pct", type=float, default=0.06)
    real_parser.add_argument("--core-sl-pct", type=float, default=0.03)
    real_parser.add_argument("--core-strong-exit-sentiment", type=float, default=-0.2)
    real_parser.add_argument("--in-pos-exit-sentiment", type=float, default=-0.05)
    real_parser.add_argument("--enable-drawdown-stop", action="store_true")
    real_parser.add_argument("--dd-max-drop-pct", type=float, default=5.0)
    real_parser.add_argument("--dd-window-min", type=float, default=15.0)
    real_parser.add_argument("--dd-window-drop-pct", type=float, default=1.0)
    real_parser.add_argument("--dd-min-consecutive-down", type=int, default=3)
    real_parser.add_argument("--dd-require-both", action="store_true")
    real_parser.add_argument("--holdings-watcher", action="store_true")
    real_parser.add_argument("--holdings-poll-seconds", type=float, default=20.0)
    args = merge_config_into_args(args, real_parser, cfg)
    NewsTrader(args).run()


if __name__ == "__main__":
    main()
